module.exports = [
  {
    auctionEndDate: new Date(+new Date() + 7*24*60*60*1000),
    origin: "ATL",
    destination: "VNY",
    flightDate: new Date(+new Date() + 9*24*60*60*1000),
    currentBid: 150.0,
    aircraft: "Gulfstream GIV-SP",
    flightNum: "N624PD",
    image: 'test.jpg',
    cabinSize: 16,
    operator: "NetJets Inc.",
    termsConfirm: false
  },
  {
    auctionEndDate: new Date(+new Date() + 8*24*60*60*1000),
    origin: "LZU",
    destination: "BNA",
    flightDate: new Date(+new Date() + 10*24*60*60*1000),
    currentBid: 250.0,
    aircraft: "Hawker 800XPi",
    flightNum: "L813VZ",
    image: 'test.jpg',
    cabinSize: 8,
    operator: "Vista Global Holding",
    termsConfirm: false
  },
  {
    auctionEndDate: new Date(+new Date() + 9*24*60*60*1000),
    origin: "FFC",
    destination: "IAD",
    flightDate: new Date(+new Date() + 11*24*60*60*1000),
    currentBid: 100.0,
    aircraft: "Bombardier Challenger 605",
    flightNum: "S224ER",
    image: 'test.jpg',
    cabinSize: 12,
    operator: "Jet Linx",
    termsConfirm: false
  },
  {
    auctionEndDate: new Date(+new Date() + 10*24*60*60*1000),
    origin: "AGS",
    destination: "DTW",
    flightDate: new Date(+new Date() + 13*24*60*60*1000),
    currentBid: 500.0,
    aircraft: "Citation Latitude",
    flightNum: "U631BW",
    image: 'test.jpg',
    cabinSize: 8,
    operator: "Solairus Aviation",
    termsConfirm: false
  },
  {
    auctionEndDate: new Date(+new Date() + 11*24*60*60*1000),
    origin: "CNI",
    destination: "IAD",
    flightDate: new Date(+new Date() + 15*24*60*60*1000),
    currentBid: 450.0,
    aircraft: "Hawker 400XP",
    flightNum: "N362EA",
    image: 'test.jpg',
    cabinSize: 8,
    operator: "Airshare",
    termsConfirm: false
  },
  {
    auctionEndDate: new Date(+new Date() + 12*24*60*60*1000),
    origin: "JES",
    destination: "LGA",
    flightDate: new Date(+new Date() + 18*24*60*60*1000),
    currentBid: 675.0,
    aircraft: "Hawker 900XP",
    flightNum: "V978TQ",
    image: 'test.jpg',
    cabinSize: 10,
    operator: "Worldwide Jet Charter",
    termsConfirm: false
  },
  {
    auctionEndDate: new Date(+new Date() + 13*24*60*60*1000),
    origin: "TOC",
    destination: "BOS",
    flightDate: new Date(+new Date() + 20*24*60*60*1000),
    currentBid: 325.0,
    aircraft: "Embraer Legacy 450",
    flightNum: "Y843AU",
    image: 'test.jpg',
    cabinSize: 12,
    operator: "Nicholas Air",
    termsConfirm: false
  },
  {
    auctionEndDate: new Date(+new Date() + 14*24*60*60*1000),
    origin: "DBN",
    destination: "TPA",
    flightDate: new Date(+new Date() + 21*24*60*60*1000),
    currentBid: 850.0,
    aircraft: "Embraer Legacy 500",
    flightNum: "U557TO",
    image: 'test.jpg',
    cabinSize: 8,
    operator: "Jet Edge",
    termsConfirm: false
  }
]
